from enum import Enum
from typing import Any
from pydantic import BaseModel

class ConstraintCategory(str, Enum):
    CUSTOMER_ACQUISITION = "CUSTOMER_ACQUISITION"
    LEAD_QUALIFICATION = "LEAD_QUALIFICATION"
    SALES_CONVERSION = "SALES_CONVERSION"
    CUSTOMER_SUPPORT = "CUSTOMER_SUPPORT"
    CUSTOMER_RETENTION = "CUSTOMER_RETENTION"
    KNOWLEDGE_MANAGEMENT = "KNOWLEDGE_MANAGEMENT"
    DOCUMENT_MANAGEMENT = "DOCUMENT_MANAGEMENT"
    OPERATIONS = "OPERATIONS"
    REPORTING = "REPORTING"
    COMPLIANCE = "COMPLIANCE"
    HIRING = "HIRING"
    TRAINING = "TRAINING"
    SCHEDULING = "SCHEDULING"
    RESOURCE_ALLOCATION = "RESOURCE_ALLOCATION"
    INVENTORY = "INVENTORY"
    FORECASTING = "FORECASTING"
    INTERNAL_COMMUNICATION = "INTERNAL_COMMUNICATION"
    DECISION_INTELLIGENCE = "DECISION_INTELLIGENCE"
    COST_EFFICIENCY = "COST_EFFICIENCY"
    REVENUE_OPTIMIZATION = "REVENUE_OPTIMIZATION"
    UNKNOWN = "UNKNOWN"

class ConstraintEvidence(BaseModel):
    source: str
    value: Any
    reason: str
