import uuid
from sqlalchemy import Column, String, Integer, Float, Boolean, Text, DateTime, JSON, ForeignKey
from app.core.database import Base
from app.models.session import GUID

class ReportTemplateORM(Base):
    __tablename__ = "report_templates"

    id = Column(GUID, primary_key=True, default=uuid.uuid4)
    name = Column(String(150), unique=True, nullable=False)
    industry = Column(String(100), nullable=False)
    structure = Column(JSON, nullable=False, default=dict) # Sections config metadata
    active = Column(Boolean, nullable=False, default=True)
    created_at = Column(DateTime(timezone=True), nullable=False)

class BusinessReportORM(Base):
    __tablename__ = "business_reports"

    id = Column(GUID, primary_key=True, default=uuid.uuid4)
    session_id = Column(GUID, ForeignKey("sessions.id", ondelete="CASCADE"), nullable=False, index=True)
    evaluation_id = Column(GUID, ForeignKey("opportunity_evaluations.id", ondelete="CASCADE"), nullable=False, index=True)
    template_id = Column(GUID, ForeignKey("report_templates.id", ondelete="SET NULL"), nullable=True)
    structured_data = Column(JSON, nullable=False) # Source of truth: snapshot, matrix, actions
    narrative_summary = Column(Text, nullable=True) # Text generated by Grok Layer
    engine_version = Column(String(50), nullable=False)
    qualification_version = Column(String(50), nullable=False)
    health_assessment_version = Column(String(50), nullable=False)
    narrative_version = Column(String(50), nullable=False)
    created_at = Column(DateTime(timezone=True), nullable=False)
    updated_at = Column(DateTime(timezone=True), nullable=False)

class ReportVersionORM(Base):
    __tablename__ = "report_versions"

    id = Column(GUID, primary_key=True, default=uuid.uuid4)
    report_id = Column(GUID, ForeignKey("business_reports.id", ondelete="CASCADE"), nullable=False, index=True)
    version_number = Column(Integer, nullable=False)
    structured_data = Column(JSON, nullable=False)
    narrative_summary = Column(Text, nullable=True)
    engine_version = Column(String(50), nullable=False)
    qualification_version = Column(String(50), nullable=False)
    health_assessment_version = Column(String(50), nullable=False)
    narrative_version = Column(String(50), nullable=False)
    created_at = Column(DateTime(timezone=True), nullable=False)

class ReportNarrativeEvidenceORM(Base):
    __tablename__ = "report_narrative_evidence"

    id = Column(GUID, primary_key=True, default=uuid.uuid4)
    report_id = Column(GUID, ForeignKey("business_reports.id", ondelete="CASCADE"), nullable=False, index=True)
    evidence_id = Column(GUID, ForeignKey("opportunity_evidence.id", ondelete="CASCADE"), nullable=False, index=True)
    paragraph_index = Column(Integer, nullable=False)
    created_at = Column(DateTime(timezone=True), nullable=False)

class QualificationResultORM(Base):
    __tablename__ = "qualification_results"

    id = Column(GUID, primary_key=True, default=uuid.uuid4)
    session_id = Column(GUID, ForeignKey("sessions.id", ondelete="CASCADE"), nullable=False, unique=True, index=True)
    qualification_score = Column(Integer, nullable=False)
    lead_grade = Column(String(50), nullable=False) # HOT, WARM, COLD
    routing_path = Column(String(50), nullable=False) # SELF_SERVE, CONSULTATION, ENTERPRISE
    factors = Column(JSON, nullable=False, default=list) # Matched evaluation checklist
    qualification_version = Column(String(50), nullable=False)
    created_at = Column(DateTime(timezone=True), nullable=False)

class BusinessHealthAssessmentORM(Base):
    __tablename__ = "business_health_assessments"

    id = Column(GUID, primary_key=True, default=uuid.uuid4)
    session_id = Column(GUID, ForeignKey("sessions.id", ondelete="CASCADE"), nullable=False, unique=True, index=True)
    communication_health = Column(Integer, nullable=False)
    automation_health = Column(Integer, nullable=False)
    operational_health = Column(Integer, nullable=False)
    growth_readiness = Column(Integer, nullable=False)
    facts = Column(JSON, nullable=False, default=dict)
    health_assessment_version = Column(String(50), nullable=False)
    created_at = Column(DateTime(timezone=True), nullable=False)

class ConsultationRecommendationORM(Base):
    __tablename__ = "consultation_recommendations"

    id = Column(GUID, primary_key=True, default=uuid.uuid4)
    session_id = Column(GUID, ForeignKey("sessions.id", ondelete="CASCADE"), nullable=False, unique=True, index=True)
    consultation_recommended = Column(Boolean, nullable=False)
    confidence = Column(Float, nullable=False)
    reasons = Column(JSON, nullable=False, default=list)
    consultation_version = Column(String(50), nullable=False)
    created_at = Column(DateTime(timezone=True), nullable=False)
